# Generated by Django 3.2.6 on 2023-11-08 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_alter_ad_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(default=1, verbose_name='отзыв'),
            preserve_default=False,
        ),
    ]
